spring.application.name=school-management-backend

# MongoDB Local Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/wesley_school

# Enable auto-index creation for @Indexed fields in documents
spring.data.mongodb.auto-index-creation=true
